apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
    version: v2
  name: python-v2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: http
      name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python
    version: v2
  sessionAffinity: None
  type: ClusterIP
