apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- service.yml

namespace: instrumentation
images:
- name: localhost/mockbin
  newName: localhost/autoinstrumentation
  newTag: nginx-124-ubi9
