apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go
    app.kubernetes.io/component: go
    topology.istio.io/subzone: zone1
    topology.kubernetes.io/region: lab
    topology.kubernetes.io/zone: zone1
    version: v1
  name: go-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go
        sidecar.istio.io/inject: 'true'
        topology.istio.io/subzone: zone1
        topology.kubernetes.io/region: lab
        topology.kubernetes.io/zone: zone1
        version: v1
      annotations:
        sidecar.istio.io/nativeSidecar: "true"
        sidecar.opentelemetry.io/inject: "mockbin"
        instrumentation.opentelemetry.io/inject-go: "tenanta"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/main"
        openshift.io/required-scc: privileged
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ZONE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
            - name: REGION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.kubernetes.io/region']
            - name: SUBZONE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.istio.io/subzone']
            - name: TZ
              value: UTC
          image: localhost/mockbin:v1.0.0
          imagePullPolicy: Always
          name: mockbin-v1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3
